import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Sparkles,
  Download,
  Share2,
  TrendingUp,
  Users,
  Building2,
  Languages,
  Rocket,
  FileText,
  CheckCircle2,
  ArrowUpRight,
  Calendar,
  MapPin,
  Quote,
} from "lucide-react";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  RadialBar,
  RadialBarChart,
  PolarAngleAxis,
} from "recharts";

export const Route = createFileRoute("/_app/report")({
  head: () => ({
    meta: [
      { title: "China Market Report — Beauty of Joseon · BridgeCN AI" },
      {
        name: "description",
        content:
          "AI-generated China market entry report for Beauty of Joseon: opportunity sizing, consumer persona, competitors, localization, and go-to-market strategy.",
      },
    ],
  }),
  component: ReportPage,
});

const marketGrowth = [
  { y: "2021", v: 48 },
  { y: "2022", v: 54 },
  { y: "2023", v: 62 },
  { y: "2024", v: 71 },
  { y: "2025", v: 83 },
  { y: "2026E", v: 96 },
  { y: "2027E", v: 112 },
];

const channels = [
  { name: "Tmall Global", v: 38 },
  { name: "Douyin", v: 27 },
  { name: "Xiaohongshu", v: 21 },
  { name: "JD Worldwide", v: 9 },
  { name: "WeChat Mini", v: 5 },
];

const competitors = [
  { brand: "SK-II", origin: "JP", share: "12.4%", price: "₩₩₩₩", strength: "Brand heritage" },
  { brand: "Estée Lauder", origin: "US", share: "10.8%", price: "₩₩₩₩", strength: "Counter network" },
  { brand: "Proya", origin: "CN", share: "9.6%", price: "₩₩", strength: "Local R&D + KOLs" },
  { brand: "COSRX", origin: "KR", share: "4.1%", price: "₩₩", strength: "Acne hero SKU" },
  { brand: "Beauty of Joseon", origin: "KR", share: "1.2%", price: "₩₩", strength: "Hanbang positioning" },
];

const localization = [
  {
    label: "Brand name",
    from: "Beauty of Joseon",
    to: "朝鲜美 (Cháoxiān Měi)",
  },
  {
    label: "Hero product",
    from: "Relief Sun: Rice + Probiotics",
    to: "大米防晒霜 · 益生菌舒缓配方",
  },
  {
    label: "Key claim",
    from: "Glow inspired by Joseon-era beauty rituals",
    to: "传承朝鲜宫廷护肤智慧的自然光感",
  },
  {
    label: "Tone",
    from: "Calm, heritage, minimal",
    to: "温润、东方、有故事感",
  },
];

const roadmap = [
  {
    phase: "Phase 1 · Weeks 1–4",
    title: "Cross-border foundation",
    items: [
      "Open Tmall Global flagship via TP partner",
      "Register WeChat Official Account + Mini Program",
      "Trademark filing in classes 3 & 5",
    ],
  },
  {
    phase: "Phase 2 · Weeks 5–10",
    title: "Seeding & social proof",
    items: [
      "Seed 120 腰部 KOCs on Xiaohongshu around Rice Toner",
      "5 mid-tier KOLs on Douyin (≥500K followers)",
      "Launch hashtag #朝鲜美光感 with UGC challenge",
    ],
  },
  {
    phase: "Phase 3 · Weeks 11–16",
    title: "Conversion & retention",
    items: [
      "Douyin livestream with Austin Li tier-2 host",
      "Tmall Super Brand Day around 618",
      "CRM flows via WeCom for repeat purchase",
    ],
  },
];

function ReportPage() {
  return (
    <div className="mx-auto max-w-5xl space-y-12 py-2 md:py-6">
      {/* Document header */}
      <header className="border-b border-[var(--border)] pb-8">
        <div className="flex flex-wrap items-center gap-2 text-xs text-[var(--muted-foreground)]">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--border)] bg-[var(--background)] px-2.5 py-1 font-medium">
            <Sparkles className="h-3 w-3 text-[var(--primary)]" />
            Generated by BridgeCN AI
          </span>
          <span className="inline-flex items-center gap-1.5">
            <Calendar className="h-3 w-3" />
            June 28, 2026
          </span>
          <span>·</span>
          <span className="inline-flex items-center gap-1.5">
            <MapPin className="h-3 w-3" />
            Greater China · Mainland
          </span>
          <span>·</span>
          <span>Confidence 92%</span>
        </div>

        <div className="mt-6 flex flex-wrap items-end justify-between gap-6">
          <div className="min-w-0">
            <div className="flex items-center gap-3">
              <div className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-[var(--muted)] to-[var(--primary-soft)] text-sm font-semibold">
                BJ
              </div>
              <div>
                <div className="text-sm font-medium text-[var(--muted-foreground)]">
                  Beauty of Joseon
                </div>
                <h1 className="text-3xl font-semibold tracking-[-0.02em] md:text-4xl">
                  China Expansion Report
                </h1>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button className="inline-flex h-9 items-center gap-1.5 rounded-full border border-[var(--border)] bg-[var(--background)] px-3.5 text-xs font-medium hover:bg-[var(--muted)]">
              <Share2 className="h-3.5 w-3.5" />
              Share
            </button>
            <button className="inline-flex h-9 items-center gap-1.5 rounded-full bg-[var(--foreground)] px-3.5 text-xs font-medium text-[var(--background)] hover:opacity-90">
              <Download className="h-3.5 w-3.5" />
              Export PDF
            </button>
          </div>
        </div>

        {/* TOC */}
        <nav className="mt-8 grid grid-cols-2 gap-2 text-xs md:grid-cols-6">
          {[
            "Executive Summary",
            "Market Opportunity",
            "Consumer Persona",
            "Competitor Analysis",
            "Localization",
            "Go-to-Market",
          ].map((s, i) => (
            <a
              key={s}
              href={`#s${i + 1}`}
              className="rounded-lg border border-[var(--border)] bg-[var(--background)] px-3 py-2 font-medium text-[var(--muted-foreground)] transition-colors hover:bg-[var(--muted)] hover:text-[var(--foreground)]"
            >
              <span className="text-[var(--muted-foreground)]">0{i + 1}</span>{" "}
              <span className="ml-1">{s}</span>
            </a>
          ))}
        </nav>
      </header>

      {/* 01 Executive Summary */}
      <Section id="s1" eyebrow="01" icon={FileText} title="Executive Summary">
        <p className="text-[15px] leading-7 text-[var(--foreground)]">
          Beauty of Joseon is well-positioned to expand into Mainland China through a
          <strong> cross-border, content-led entry</strong>. Hanbang-inspired skincare
          enjoys rising affinity among Gen-Z and millennial Chinese consumers, with{" "}
          <strong>+24.8% YoY</strong> mentions on Xiaohongshu and a Tmall Global category
          growing at <strong>17% CAGR</strong>. We recommend launching with{" "}
          <strong>Rice Toner</strong> and <strong>Relief Sun</strong> as hero SKUs, anchored
          by a Xiaohongshu KOC seeding wave and a Douyin livestream activation around 618.
        </p>
        <div className="mt-6 grid gap-3 sm:grid-cols-4">
          {[
            { k: "Market size", v: "₩4.2T", s: "2026E, K-beauty CN" },
            { k: "Entry investment", v: "₩820M", s: "First 6 months" },
            { k: "Break-even", v: "Month 11", s: "Base case" },
            { k: "Confidence", v: "92%", s: "AI score" },
          ].map((x) => (
            <div
              key={x.k}
              className="rounded-xl border border-[var(--border)] bg-[var(--background)] p-4"
            >
              <div className="text-[11px] text-[var(--muted-foreground)]">{x.k}</div>
              <div className="mt-1 text-xl font-semibold tracking-tight">{x.v}</div>
              <div className="text-[11px] text-[var(--muted-foreground)]">{x.s}</div>
            </div>
          ))}
        </div>
      </Section>

      {/* 02 Market Opportunity */}
      <Section id="s2" eyebrow="02" icon={TrendingUp} title="Market Opportunity">
        <p className="text-[15px] leading-7 text-[var(--muted-foreground)]">
          The Chinese imported skincare market is forecast to reach{" "}
          <span className="text-[var(--foreground)] font-medium">₩112T by 2027</span>, with
          K-beauty regaining share after the 2022 trough. Hanbang and "clean glow"
          positioning over-index in Tier 1 and new Tier 1 cities.
        </p>
        <div className="mt-6 grid gap-4 lg:grid-cols-5">
          <Card className="lg:col-span-3">
            <CardHeader title="K-beauty market in China" sub="₩ Trillion · 2021–2027E" />
            <div className="h-60 px-2 pb-2">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={marketGrowth} margin={{ top: 8, right: 12, bottom: 0, left: -10 }}>
                  <defs>
                    <linearGradient id="mg" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="var(--primary)" stopOpacity={0.35} />
                      <stop offset="100%" stopColor="var(--primary)" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 3" />
                  <XAxis dataKey="y" stroke="var(--muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
                  <YAxis stroke="var(--muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
                  <Tooltip
                    contentStyle={{
                      background: "var(--background)",
                      border: "1px solid var(--border)",
                      borderRadius: 8,
                      fontSize: 12,
                    }}
                  />
                  <Area type="monotone" dataKey="v" stroke="var(--primary)" strokeWidth={2} fill="url(#mg)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </Card>
          <Card className="lg:col-span-2">
            <CardHeader title="Channel mix" sub="Recommended GMV split · Year 1" />
            <div className="h-60 px-2 pb-2">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={channels} layout="vertical" margin={{ top: 8, right: 12, bottom: 0, left: 12 }}>
                  <XAxis type="number" hide />
                  <YAxis
                    type="category"
                    dataKey="name"
                    stroke="var(--muted-foreground)"
                    fontSize={11}
                    tickLine={false}
                    axisLine={false}
                    width={86}
                  />
                  <Bar dataKey="v" fill="var(--foreground)" radius={[0, 4, 4, 0]} barSize={14} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </div>
      </Section>

      {/* 03 Consumer Persona */}
      <Section id="s3" eyebrow="03" icon={Users} title="Consumer Persona">
        <div className="grid gap-4 md:grid-cols-3">
          <div className="rounded-2xl border border-[var(--border)] bg-gradient-to-br from-[var(--background)] to-[var(--primary-soft)]/40 p-6 md:col-span-1">
            <div className="text-xs font-medium text-[var(--primary)]">Primary persona</div>
            <div className="mt-2 text-xl font-semibold tracking-tight">小雅 · Xiao Ya</div>
            <div className="mt-1 text-xs text-[var(--muted-foreground)]">
              26 · Shanghai · Marketing associate
            </div>
            <div className="mt-5 space-y-3 text-sm">
              <Row k="Income" v="¥18k / month" />
              <Row k="Skin" v="Sensitive · combination" />
              <Row k="Spend on skincare" v="¥600–900 / month" />
              <Row k="Top platforms" v="小红书, 抖音, 微信" />
            </div>
          </div>
          <div className="grid gap-4 md:col-span-2">
            <div className="rounded-2xl border border-[var(--border)] bg-[var(--background)] p-6">
              <div className="text-xs font-medium uppercase tracking-wider text-[var(--muted-foreground)]">
                What she values
              </div>
              <ul className="mt-3 grid gap-2 text-sm sm:grid-cols-2">
                {[
                  "Gentle, low-irritation formulas",
                  "Korean and East-Asian heritage cues",
                  "Transparent ingredient lists",
                  "Real-user reviews on 小红书",
                ].map((t) => (
                  <li key={t} className="flex items-start gap-2">
                    <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[var(--primary)]" />
                    <span>{t}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="rounded-2xl border border-[var(--border)] bg-[var(--background)] p-6">
              <Quote className="h-4 w-4 text-[var(--muted-foreground)]" />
              <p className="mt-2 text-[15px] leading-7">
                "我喜欢有故事感的韩国护肤品 — 成分温和、上脸舒服，包装也好看到能放在桌面上。"
              </p>
              <div className="mt-2 text-xs text-[var(--muted-foreground)]">
                Synthesized from 412 Xiaohongshu reviews in the K-beauty cluster
              </div>
            </div>
          </div>
        </div>
      </Section>

      {/* 04 Competitor Analysis */}
      <Section id="s4" eyebrow="04" icon={Building2} title="Competitor Analysis">
        <div className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--background)]">
          <div className="grid grid-cols-[1.4fr_0.6fr_0.7fr_0.6fr_1.5fr] gap-4 border-b border-[var(--border)] px-5 py-3 text-[11px] font-medium uppercase tracking-wider text-[var(--muted-foreground)]">
            <div>Brand</div>
            <div>Origin</div>
            <div>Share</div>
            <div>Price</div>
            <div>Key strength</div>
          </div>
          <ul className="divide-y divide-[var(--border)]">
            {competitors.map((c) => {
              const us = c.brand === "Beauty of Joseon";
              return (
                <li
                  key={c.brand}
                  className={`grid grid-cols-[1.4fr_0.6fr_0.7fr_0.6fr_1.5fr] items-center gap-4 px-5 py-4 text-sm ${
                    us ? "bg-[var(--primary-soft)]/40" : ""
                  }`}
                >
                  <div className="flex items-center gap-2 font-medium">
                    {c.brand}
                    {us && (
                      <span className="rounded-full bg-[var(--primary)] px-1.5 py-0.5 text-[10px] font-semibold text-[var(--primary-foreground)]">
                        You
                      </span>
                    )}
                  </div>
                  <div className="text-[var(--muted-foreground)]">{c.origin}</div>
                  <div className="tabular-nums">{c.share}</div>
                  <div className="text-[var(--muted-foreground)]">{c.price}</div>
                  <div className="text-[var(--muted-foreground)]">{c.strength}</div>
                </li>
              );
            })}
          </ul>
        </div>
        <div className="mt-4 rounded-xl border border-dashed border-[var(--border)] bg-[var(--muted)]/40 p-4 text-sm text-[var(--muted-foreground)]">
          <span className="font-medium text-[var(--foreground)]">AI insight · </span>
          The white space sits between premium Japanese heritage brands and mass-market
          local players. Hanbang storytelling + accessible pricing (¥150–280) is a
          defensible mid-premium wedge.
        </div>
      </Section>

      {/* 05 Localization */}
      <Section id="s5" eyebrow="05" icon={Languages} title="Localization Recommendations">
        <div className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--background)]">
          {localization.map((l, i) => (
            <div
              key={l.label}
              className={`grid grid-cols-[140px_1fr_auto_1fr] items-center gap-4 px-5 py-4 text-sm ${
                i !== 0 ? "border-t border-[var(--border)]" : ""
              }`}
            >
              <div className="text-xs font-medium uppercase tracking-wider text-[var(--muted-foreground)]">
                {l.label}
              </div>
              <div className="text-[var(--muted-foreground)]">{l.from}</div>
              <ArrowUpRight className="h-3.5 w-3.5 text-[var(--muted-foreground)]" />
              <div className="font-medium">{l.to}</div>
            </div>
          ))}
        </div>
      </Section>

      {/* 06 Go-to-Market */}
      <Section id="s6" eyebrow="06" icon={Rocket} title="Go-to-Market Strategy">
        <div className="grid gap-4 lg:grid-cols-[1fr_280px]">
          <ol className="relative space-y-4 border-l border-[var(--border)] pl-6">
            {roadmap.map((r) => (
              <li key={r.phase} className="relative">
                <span className="absolute -left-[26px] top-1.5 grid h-3 w-3 place-items-center rounded-full border-2 border-[var(--background)] bg-[var(--foreground)]" />
                <div className="text-[11px] font-medium uppercase tracking-wider text-[var(--muted-foreground)]">
                  {r.phase}
                </div>
                <div className="mt-0.5 text-base font-semibold tracking-tight">{r.title}</div>
                <ul className="mt-2 space-y-1.5 text-sm text-[var(--muted-foreground)]">
                  {r.items.map((it) => (
                    <li key={it} className="flex items-start gap-2">
                      <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--primary)]" />
                      <span>{it}</span>
                    </li>
                  ))}
                </ul>
              </li>
            ))}
          </ol>
          <Card>
            <CardHeader title="Year 1 outlook" sub="Base-case projection" />
            <div className="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <RadialBarChart
                  innerRadius="60%"
                  outerRadius="100%"
                  data={[{ name: "Goal", v: 76, fill: "var(--primary)" }]}
                  startAngle={90}
                  endAngle={-270}
                >
                  <PolarAngleAxis type="number" domain={[0, 100]} tick={false} />
                  <RadialBar background dataKey="v" cornerRadius={20} />
                </RadialBarChart>
              </ResponsiveContainer>
            </div>
            <div className="-mt-32 text-center">
              <div className="text-2xl font-semibold tracking-tight">₩6.4B</div>
              <div className="text-[11px] text-[var(--muted-foreground)]">
                Projected GMV · 76% to target
              </div>
            </div>
            <div className="mt-16 space-y-2 px-5 pb-5 text-xs text-[var(--muted-foreground)]">
              <Row k="ROAS" v="3.1x" />
              <Row k="Repeat rate" v="28%" />
              <Row k="Followers · Year 1" v="180k" />
            </div>
          </Card>
        </div>
      </Section>

      {/* Footer actions */}
      <footer className="flex flex-col items-center gap-4 border-t border-[var(--border)] pt-10">
        <div className="text-center text-xs text-[var(--muted-foreground)]">
          Report generated by BridgeCN AI · 6 sections · 12 data sources
        </div>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <button className="inline-flex h-11 items-center gap-2 rounded-full bg-[var(--foreground)] px-5 text-sm font-medium text-[var(--background)] shadow-[var(--shadow-card)] transition-transform hover:-translate-y-0.5">
            <Download className="h-4 w-4" />
            Export PDF
          </button>
          <button className="inline-flex h-11 items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--background)] px-5 text-sm font-medium hover:bg-[var(--muted)]">
            <Share2 className="h-4 w-4" />
            Share Report
          </button>
          <Link
            to="/"
            className="text-sm font-medium text-[var(--muted-foreground)] hover:text-[var(--foreground)]"
          >
            Back to dashboard
          </Link>
        </div>
      </footer>
    </div>
  );
}

function Section({
  id,
  eyebrow,
  icon: Icon,
  title,
  children,
}: {
  id: string;
  eyebrow: string;
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-20">
      <div className="mb-5 flex items-center gap-3">
        <div className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)] bg-[var(--background)] text-[var(--foreground)]">
          <Icon className="h-4 w-4" />
        </div>
        <div>
          <div className="text-[11px] font-medium uppercase tracking-wider text-[var(--muted-foreground)]">
            Section {eyebrow}
          </div>
          <h2 className="text-xl font-semibold tracking-tight md:text-2xl">{title}</h2>
        </div>
      </div>
      {children}
    </section>
  );
}

function Card({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={`overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--background)] ${className}`}
    >
      {children}
    </div>
  );
}

function CardHeader({ title, sub }: { title: string; sub: string }) {
  return (
    <div className="px-5 pt-5">
      <div className="text-sm font-semibold tracking-tight">{title}</div>
      <div className="text-[11px] text-[var(--muted-foreground)]">{sub}</div>
    </div>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex items-center justify-between gap-3">
      <span className="text-[var(--muted-foreground)]">{k}</span>
      <span className="font-medium text-[var(--foreground)]">{v}</span>
    </div>
  );
}
