import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Sparkles,
  Download,
  Share2,
  FileText,
  Calendar,
  MapPin,
} from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { ProjectContextBar } from "@/components/project-context-bar";
import { useI18n } from "@/lib/i18n";
import { useWorkspace } from "@/lib/workspace-context";

export const Route = createFileRoute("/_app/report")({
  head: () => ({
    meta: [
      { title: "Report — BridgeCN AI" },
      {
        name: "description",
        content:
          "AI-generated China market entry reports for your active project, built from the Project Knowledge Base.",
      },
    ],
  }),
  component: ReportPage,
});

function ReportPage() {
  const { t } = useI18n();
  const { activeProject } = useWorkspace();
  const kb = activeProject?.knowledgeBase || {};

  // Sprint 9: report content is project-driven. Until a report has been
  // generated for this project via the AI engine, show an empty state
  // that points the user back to enriching the Knowledge Base.
  const hasReport = false;

  return (
    <div>
      <ProjectContextBar />
      <PageHeader
        title={activeProject?.name ? `${activeProject.name} · ${t("reports.title")}` : t("reports.title")}
        description={t("reports.sub")}
      />
      <div className="mx-auto max-w-5xl space-y-8 py-2 md:py-6">
        <header className="border-b border-[var(--border)] pb-8">
          <div className="flex flex-wrap items-center gap-2 text-xs text-[var(--muted-foreground)]">
            <span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--border)] bg-[var(--background)] px-2.5 py-1 font-medium">
              <Sparkles className="h-3 w-3 text-[var(--primary)]" />
              Generated by BridgeCN AI
            </span>
            <span className="inline-flex items-center gap-1.5">
              <Calendar className="h-3 w-3" />
              {new Date().toLocaleDateString()}
            </span>
            {kb.industry && (
              <>
                <span>·</span>
                <span className="inline-flex items-center gap-1.5">
                  <MapPin className="h-3 w-3" />
                  {activeProject?.targetMarket || activeProject?.region || "—"}
                </span>
              </>
            )}
          </div>

          <div className="mt-6 flex flex-wrap items-end justify-between gap-6">
            <div className="min-w-0">
              <div className="flex items-center gap-3">
                <div className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-[var(--muted)] to-[var(--primary-soft)] text-sm font-semibold">
                  {activeProject?.initials || "—"}
                </div>
                <div>
                  <div className="text-sm font-medium text-[var(--muted-foreground)]">
                    {activeProject?.name || "—"}
                  </div>
                  <h1 className="text-3xl font-semibold tracking-[-0.02em] md:text-4xl">
                    {t("reports.title")}
                  </h1>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button className="inline-flex h-9 items-center gap-1.5 rounded-full border border-[var(--border)] bg-[var(--background)] px-3.5 text-xs font-medium hover:bg-[var(--muted)]">
                <Share2 className="h-3.5 w-3.5" />
                {t("common.share")}
              </button>
              <button className="inline-flex h-9 items-center gap-1.5 rounded-full bg-[var(--foreground)] px-3.5 text-xs font-medium text-[var(--background)] hover:opacity-90">
                <Download className="h-3.5 w-3.5" />
                {t("common.export")} PDF
              </button>
            </div>
          </div>
        </header>

        {!hasReport ? (
          <div className="rounded-2xl border border-dashed border-[var(--border)] bg-[var(--background)] p-10 text-center shadow-[var(--shadow-soft)]">
            <FileText className="mx-auto h-5 w-5 text-[var(--primary)]" />
            <p className="mt-3 text-sm font-medium">
              No report generated yet for {activeProject?.name || "this project"}.
            </p>
            <p className="mt-1 text-xs text-[var(--muted-foreground)]">
              Enrich the Project Knowledge Base and generate market insight to assemble a full report.
            </p>
            <div className="mt-4 flex flex-wrap items-center justify-center gap-2">
              {activeProject?.id && (
                <Link
                  to="/projects/$projectId"
                  params={{ projectId: activeProject.id }}
                  className="inline-flex h-9 items-center rounded-md border border-[var(--border)] px-3 text-xs font-medium hover:bg-[var(--muted)]"
                >
                  Open Knowledge Base
                </Link>
              )}
              <Link
                to="/china-market-insight"
                className="inline-flex h-9 items-center rounded-md bg-[var(--foreground)] px-3 text-xs font-medium text-[var(--background)] hover:opacity-90"
              >
                Generate Market Insight
              </Link>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}
