/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStartRouteImport } from './routes/_app.start'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLocalizationStudioRouteImport } from './routes/_app.localization-studio'
import { Route as AppLaunchChecklistRouteImport } from './routes/_app.launch-checklist'
import { Route as AppConsumerInsightRouteImport } from './routes/_app.consumer-insight'
import { Route as AppCompetitorsRouteImport } from './routes/_app.competitors'
import { Route as AppChinaMarketInsightRouteImport } from './routes/_app.china-market-insight'
import { Route as AppAiWorkspaceRouteImport } from './routes/_app.ai-workspace'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStartRoute = AppStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLocalizationStudioRoute = AppLocalizationStudioRouteImport.update({
  id: '/localization-studio',
  path: '/localization-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppLaunchChecklistRoute = AppLaunchChecklistRouteImport.update({
  id: '/launch-checklist',
  path: '/launch-checklist',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumerInsightRoute = AppConsumerInsightRouteImport.update({
  id: '/consumer-insight',
  path: '/consumer-insight',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppChinaMarketInsightRoute = AppChinaMarketInsightRouteImport.update({
  id: '/china-market-insight',
  path: '/china-market-insight',
  getParentRoute: () => AppRoute,
} as any)
const AppAiWorkspaceRoute = AppAiWorkspaceRouteImport.update({
  id: '/ai-workspace',
  path: '/ai-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/ai-workspace': typeof AppAiWorkspaceRoute
  '/china-market-insight': typeof AppChinaMarketInsightRoute
  '/competitors': typeof AppCompetitorsRoute
  '/consumer-insight': typeof AppConsumerInsightRoute
  '/launch-checklist': typeof AppLaunchChecklistRoute
  '/localization-studio': typeof AppLocalizationStudioRoute
  '/notifications': typeof AppNotificationsRoute
  '/report': typeof AppReportRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/start': typeof AppStartRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/ai-workspace': typeof AppAiWorkspaceRoute
  '/china-market-insight': typeof AppChinaMarketInsightRoute
  '/competitors': typeof AppCompetitorsRoute
  '/consumer-insight': typeof AppConsumerInsightRoute
  '/launch-checklist': typeof AppLaunchChecklistRoute
  '/localization-studio': typeof AppLocalizationStudioRoute
  '/notifications': typeof AppNotificationsRoute
  '/report': typeof AppReportRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/start': typeof AppStartRoute
  '/': typeof AppIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects': typeof AppProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/_app/ai-workspace': typeof AppAiWorkspaceRoute
  '/_app/china-market-insight': typeof AppChinaMarketInsightRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/consumer-insight': typeof AppConsumerInsightRoute
  '/_app/launch-checklist': typeof AppLaunchChecklistRoute
  '/_app/localization-studio': typeof AppLocalizationStudioRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/report': typeof AppReportRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/start': typeof AppStartRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/ai-workspace'
    | '/china-market-insight'
    | '/competitors'
    | '/consumer-insight'
    | '/launch-checklist'
    | '/localization-studio'
    | '/notifications'
    | '/report'
    | '/reports'
    | '/settings'
    | '/start'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/ai-workspace'
    | '/china-market-insight'
    | '/competitors'
    | '/consumer-insight'
    | '/launch-checklist'
    | '/localization-studio'
    | '/notifications'
    | '/report'
    | '/reports'
    | '/settings'
    | '/start'
    | '/'
    | '/projects/$projectId'
    | '/projects'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/_app/ai-workspace'
    | '/_app/china-market-insight'
    | '/_app/competitors'
    | '/_app/consumer-insight'
    | '/_app/launch-checklist'
    | '/_app/localization-studio'
    | '/_app/notifications'
    | '/_app/report'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/start'
    | '/_app/'
    | '/_app/projects/$projectId'
    | '/_app/projects/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/start': {
      id: '/_app/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AppStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/localization-studio': {
      id: '/_app/localization-studio'
      path: '/localization-studio'
      fullPath: '/localization-studio'
      preLoaderRoute: typeof AppLocalizationStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/launch-checklist': {
      id: '/_app/launch-checklist'
      path: '/launch-checklist'
      fullPath: '/launch-checklist'
      preLoaderRoute: typeof AppLaunchChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumer-insight': {
      id: '/_app/consumer-insight'
      path: '/consumer-insight'
      fullPath: '/consumer-insight'
      preLoaderRoute: typeof AppConsumerInsightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/china-market-insight': {
      id: '/_app/china-market-insight'
      path: '/china-market-insight'
      fullPath: '/china-market-insight'
      preLoaderRoute: typeof AppChinaMarketInsightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-workspace': {
      id: '/_app/ai-workspace'
      path: '/ai-workspace'
      fullPath: '/ai-workspace'
      preLoaderRoute: typeof AppAiWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiWorkspaceRoute: typeof AppAiWorkspaceRoute
  AppChinaMarketInsightRoute: typeof AppChinaMarketInsightRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppConsumerInsightRoute: typeof AppConsumerInsightRoute
  AppLaunchChecklistRoute: typeof AppLaunchChecklistRoute
  AppLocalizationStudioRoute: typeof AppLocalizationStudioRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportRoute: typeof AppReportRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStartRoute: typeof AppStartRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiWorkspaceRoute: AppAiWorkspaceRoute,
  AppChinaMarketInsightRoute: AppChinaMarketInsightRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppConsumerInsightRoute: AppConsumerInsightRoute,
  AppLaunchChecklistRoute: AppLaunchChecklistRoute,
  AppLocalizationStudioRoute: AppLocalizationStudioRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportRoute: AppReportRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStartRoute: AppStartRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
